# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish

on:
  workflow_dispatch:
    inputs:
      release:
        type: string
        required: true
        description: 'release version of the builder package'
        default: '0'
      iso_type:
        type: choice
        description: Choose type of ISO image
        options:
        - core
        - full

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    environment: versions
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Setup Docker Buildx environment
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          build-args: |
            iso_type=${{ github.event.inputs.iso_type }}
          tags: mailsvb/isobuilder:${{ github.event.inputs.iso_type }}-r${{ github.event.inputs.release }}
